### ISSUE TITLE
Lister mode doesn't work

### ISSUE THREAD

**Issue by andoro** [adrianbj/BatchChildEditor#16] opened 2020-08-04 19:45 UTC
I've installed Lister Pro module, my goal is to batch edit listed pages.
However Auto Page Rename module doesn't play nicely with Lister Pro, so I decided to try BatchChildEditor in Lister mode..
I read here that if I have Lister Pro, I'm able to edit inline the pages in this mode. https://devhub.io/repos/adrianbj-BatchChildEditor
I can't, I get this error:

![image](https://user-images.githubusercontent.com/775765/89337765-c6b13a80-d69b-11ea-894b-9437ef74aee1.png)

**Comment by adrianbj** [comment] 2020-08-05 05:28
@andoro - it's working here for me:

![image](https://user-images.githubusercontent.com/871211/89375080-c9169300-d6a1-11ea-9d95-767e6d8ed990.png)

Any chance you could do a little debugging to see where that error is coming from?

**Comment by andoro** [comment] 2020-08-05 13:00
I can't find any errors in the log, at least there are no JS console errors and in the error log of PHP.

**Comment by adrianbj** [comment] 2020-08-07 14:32
@andoro - not sure how to help at the moment. It makes me think Lister's path has been moved. Do you have Tracy Debugger installed to capture any notices/warnings?

**Comment by adrianbj** [comment] 2020-08-31 22:37
@andoro - did you find out anything more on this? It's still working fine for me so it's hard to debug without more info.

**Comment by adrianbj** [comment] 2020-09-21 21:22
@andoro - any news? I am going to close this soon if I don't hear from you, because it's all working at my end.

**Comment by adrianbj** [comment] 2020-09-26 19:43
@andoro - I'm closing this now - if you're still having problems and can help me to reproduce, feel free to add another comment and I'll take another look.

**Closed as completed by adrianbj** 2020-09-26 19:43 UTC
