### ISSUE TITLE
 Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by fijha** [adrianbj/BatchChildEditor#13] opened 2018-05-02 22:59 UTC
`Notice: Trying to get property of non-object in /…/modules/BatchChildEditor.module on line 860`

I'm getting this error when editing pages that have children without `title` field. Should by simple to fix with some conditioning. So `title` should not be expected as default on every page because it can be removed from templates.

**Comment by adrianbj** [comment] 2018-05-07 17:37
Hi @fijha - thanks for the report. I can't reproduce at the moment. I am testing with a template without a title field but not seeing that notice. I think it might actually be a multilanguage issue. Do you have multi-language support installed?

Any chance you could narrow down exactly which call is triggering it. I feel like maybe it's `$cp->title->getLanguageValue($userLang)` but it would be helpful if you could narrow it down please.

**Comment by fijha** [comment] 2018-05-07 18:36
Hi, I don' have multi-language support installed and never had. I'm only seeing this notice when trying to edit parent pages that have direct children without title field in their templates. And when I click on "Children" tab I get this error second time.

I tried to split that line to multiple lines and it looks like `$userLang->title` is triggering it.

So there is a problem with that line:

`(($this->wire('languages') && $this->wire('languages')->count() > 1 && $this->titleMultiLanguage && $cp->title && !$cp->title->getLanguageValue($userLang)) || !$cp->title ? '&nbsp;<i class="fa fa-info-circle" title="No title for '.$userLang->title.'" style="color:#cccccc" aria-hidden="true"></i>' : '')`

– for some reason `$cp->title` evaluate to `true`

BatchChildEditor 1.8.10
ProcessWire 3.0.98

**Comment by adrianbj** [comment] 2018-05-07 18:44
> – for some reason $cp->title evaluate to true

Yeah, I feel like that should be null rather than true.

**Comment by fijha** [comment] 2018-05-07 18:49
Sorry, my bad… it's actually `NULL` so `$userLang->title` is triggering it.

**Comment by adrianbj** [comment] 2018-05-07 21:06
Sorry, in the middle of too many other things here. I guess maybe the root of the problem is the ` || !$cp->title`

Removing that should fix it, but there must also be a reason for it that I need to remind myself of :)

**Comment by fijha** [comment] 2018-05-08 11:14
Yes, I tried that, but not sure why it's there and if it could break something else :)

**Comment by adrianbj** [comment] 2018-06-26 05:54
Hi @fijha - this should be fixed now. Sorry it took me so long to get to. Could you please try the latest version and let me know?

**Closed as completed by adrianbj** 2018-06-26 05:54 UTC

**Comment by fijha** [comment] 2018-06-26 13:01
Hi, thank you. Yes, it works as expected.
